#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ +5%
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ -5%
fi

statusLine=$(amixer get Master | tail -n 1)
statusCmd="pactl list sinks"
mute=$($statusCmd | grep Mute: | grep -wo yes)
volume=$($statusCmd | grep Volume | head -n1 | awk -F '/' '{print $2}' | tr -d ' %')

if [[ "${mute}" == "" ]]; then
  echo "${volume}%"
  echo "${volume}%"
  echo ""
else
  echo "off"
  echo "off"
  echo ""
fi
