#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_TIME=$( echo "${BATTERY_INFO}" | grep -o "[[:digit:]]\+:[[:digit:]]\+:[[:digit:]]\+")

URGENT_VALUE=10

case "${BATTERY_STATE}" in
    "Charging")     SUFFIX="+";;
    "Discharging")  SUFFIX="-";;
    *)              SUFFIX="" ;;
esac

echo "${BATTERY_POWER}%${SUFFIX} ${BATTERY_TIME}"
echo "${BATTERY_POWER}%${SUFFIX} ${BATTERY_TIME}"
echo ""

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
