#!/bin/bash

IP_ADDRESS="$(hostname --ip-addresses)"

if [[ "${IP_ADDRESS}" == "" ]]; then
    IP_ADDRESS=$(ip route get 1 | awk '{print $NF;exit}')
fi

if [[ "${IP_ADDRESS}" != "" ]]; then
  echo "${IP_ADDRESS}"
  echo "${IP_ADDRESS}"
  echo ""
fi
